export const Terms = {
    home: { en: 'Home', ku: 'سەرەتا', ar: 'al khana' },
    accounts: { en: 'accounts', ku: 'هەژمارەکان', ar: 'accounts' },
    account_name: { en: 'account name', ku: 'ناوی هەژمار', ar: 'account name' },
    account: { en: 'accounts', ku: 'هەژمار', ar: 'accounts' },
    settings: { en: 'settings', ku: 'ڕێکخستن', ar: 'settings' },
    logout: { en: 'logout', ku: 'دەرچون', ar: 'logout' },
    Role: { en: 'Role', ku: 'دەور', ar: 'Role' },
    role: { en: 'role', ku: 'دەور', ar: 'role' },
    Roles: { en: 'Roles', ku: 'دەورەکان', ar: 'Roles' },
    roles: { en: 'roles', ku: 'دەورەکان', ar: 'roles' },
    Users: { en: 'Users', ku: 'بەکارهێنەرەکان', ar: 'Users' },
    User: { en: 'User', ku: 'بەکارهێنەر', ar: 'User' },
    user: { en: 'user', ku: 'بەکارهێنەر', ar: 'user' },
    Activity: { en: 'Activity', ku: 'چاڵاکێکان', ar: 'Activity' },
    name: { en: 'name', ku: 'ناو', ar: 'name' },
    description: { en: 'description', ku: 'پێناسه', ar: 'description' },
    ID: { en: 'ID', ku: 'ژ.م', ar: 'ID' },
    created_at: { en: 'created at', ku: 'دروستکراوە لە', ar: 'created at' },
    updated_at: { en: 'updated at', ku: 'گۆراوە لە', ar: 'updated at' },
    resources: { en: 'resources', ku: 'ڕێگەپێدانەکان', ar: 'resources' },
    action: { en: 'action', ku: 'کردەوە', ar: 'action' },
    create: { en: 'create', ku: 'دروست کردنی', ar: 'create' },
    role_name: { en: 'role_name', ku: 'ناوی دەور', ar: 'role_name' },
    excel: { en: 'excel', ku: 'ئيكسێل', ar: 'excel' },
    add: { en: 'add', ku: 'زیاد کردنی', ar: 'add' },
    search: { en: 'search', ku: 'گەڕان', ar: 'search' },
    Items_per_page: { en: 'Items per page', ku: 'ڕیز لە لاپەرە', ar: 'Items per page' },
    username: { en: 'username', ku: 'بەکارهێنەر', ar: 'username' },
    language: { en: 'language', ku: 'زمان', ar: 'language' },
    Edit: { en: 'Edit', ku: 'گۆرانکاری', ar: 'Edit' },
    edit: { en: 'edit', ku: 'گۆرانکاری', ar: 'edit' },
    delete: { en: 'delete', ku: 'سڕینەوە', ar: 'delete' },
    password: { en: 'password', ku: 'تێپەڕەوشە', ar: 'password' },
    English: { en: 'English', ku: 'ئینگلیزی', ar: 'English' },
    Kurdish: { en: 'Kurdish', ku: 'کوردی', ar: 'Kurdish' },
    Arabic: { en: 'Arabic', ku: 'عەرەبی', ar: 'Arabic' },
    Are_you_sure_you_want_to_permanently_delete_this_item : {
      en: 'Are you sure you want to permanently delete this item?',
      ku: 'ئایا دڵنیای لە سڕینەوە؟ دوای سڕینەوە ناگەڕێتەوە؟',
      ar: 'Are you sure you want to permanently delete this item?'
    },
    event: { en: 'event', ku: 'رووداو', ar: 'event' },
    IP: { en: 'IP', ku: 'IP', ar: 'IP' },
    URI: { en: 'URI', ku: 'URI', ar: 'URI' },
    before: { en: 'before', ku: 'پێشتر', ar: 'before' },
    after: { en: 'after', ku: 'دواتر', ar: 'after' },
    type: { en: 'type', ku: 'جۆر', ar: 'type' },
    phone: { en: 'phone', ku: 'مۆبایل', ar: 'phone' },
    currency: { en: 'currency', ku: 'دراو', ar: 'currency' },
    address: { en: 'address', ku: 'ناونیشان', ar: 'address' },
    all: { en: 'all', ku: 'هەموو', ar: 'all' },
    asset: { en: 'asset', ku: 'سامان', ar: 'asset' },
    liability: { en: 'liability', ku: 'قەرز', ar: 'liability' },
    equity: { en: 'equity', ku: 'دارایی', ar: 'equity' },
    expense: { en: 'expense', ku: 'خەرجی', ar: 'expense' },
    income: { en: 'income', ku: 'داهات', ar: 'income' },
    submit: { en: 'submit', ku: 'خەزن', ar: 'submit' },
    close: { en: 'close', ku: 'داخستن', ar: 'close' },
    created_by: { en: 'created_by', ku: 'دروستکەر', ar: 'created_by' },
    date: { en: 'date', ku: 'بەروار', ar: 'date' },
    increase: { en: 'increase', ku: 'زیادکردن', ar: 'increase' },
    decrease: { en: 'decrease', ku: 'کەمکردن', ar: 'decrease' },
    balance: { en: 'balance', ku: 'باڵانس', ar: 'balance' },
    today_transactions: { en: 'today transactions', ku: 'مامەڵەکانی ئەورۆ', ar: 'today transactions' },
    summary: { en: 'summary', ku: 'امانت', ar: 'summary' },
    credit: { en: 'credit', ku: 'لامان', ar: 'credit' },
    debit: { en: 'debit', ku: 'لای', ar: 'debit' },
    balance_sheet: { en: 'balance sheet', ku: 'بەلانس شیت', ar: 'balance sheet' },


    login: { en: 'login', ku: 'daxl boon', ar: 'login' },
    sign_in: { en: 'sign in', ku: 'daxl ba', ar: 'sign in' },
    code: { en: 'code', ku: 'code', ar: 'code' },
    create_role: { en: 'create role', ku: 'drwst krdni role', ar: 'create role' },
    dashboard: { en: 'dashboard', ku: 'dashboard', ar: 'dashboard' },

    // Cafe Domain
    cafe: { en: 'cafe', ku: 'cafe', ar: 'cafe' },
    food: { en: 'food', ku: 'food', ar: 'food' },
    price: { en: 'price', ku: 'price', ar: 'price' },
    new_order: { en: 'new_order', ku: 'new_order', ar: 'new_order' },
    customer: { en: 'customer', ku: 'kryar', ar: 'customer' },
    table: { en: 'table', ku: 'mez', ar: 'table' },
    discount: { en: 'discount', ku: 'dashkandn', ar: 'discount' },
    iraqi_dinar: { en: 'iraqi dinar', ku: 'iraqi dinar', ar: 'iraqi dinar' },
    print: { en: 'print', ku: 'chap', ar: 'print' },
    qty: { en: 'qty', ku: 'zhmara', ar: 'qty' },
    total: { en: 'total', ku: 'ko', ar: 'total' },
    grand_total: { en: 'grand total', ku: 'koy gshti', ar: 'grand total' },

};

